### ISSUE TITLE
Error occurred when executing BNK_Unsampler:

### ISSUE THREAD

**Issue by BNP1111** [BlenderNeko/ComfyUI_Noise#27]
Error occurred when executing BNK_Unsampler:

module 'comfy.sample' has no attribute 'convert_cond'

File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise\nodes.py", line 221, in unsampler
positive = comfy.sample.convert_cond(positive)
^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by IntellectusPrime** [comment]
i have the same problem, seems to happen since the newest comfy update.

**Comment by alexruimy** [comment]
happening here on an M1 mac too.

**Comment by Evilinside3357** [comment]
I have the same problem here too:

!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Noise/nodes.py", line 221, in unsampler
    positive = comfy.sample.convert_cond(positive)
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'

Prompt executed in 495.29 seconds

**Comment by Blakeem** [comment]
I have a pull request, that resolved the issue for me.

https://github.com/BlenderNeko/ComfyUI_Noise/pull/29

**Comment by TheChrisHatfield** [comment]
You'll need to modify the "nodes.py" file based on error looks likes its calling to a function which has be deprecated or syntax  change.  "  line 221 positive = comfy.sample.convert_cond(positive) Line 222 negative = comfy.sample.convert_cond(negative).

Dig through the changelog for Comfy UI, and find the equivalent or alternative, which is the big problem to solve.

**Comment by paulKra** [comment]
i had the same problem, you can replace the unsampler from this extensions with a combination of nodes from sample/custom_sampling, mostly SplitSigmas and flipSigmas, i couldn't find a way to replace the inject_noise node though, all options from standard comfy allow either no noise or full noise, but no partial additions. Does anyone know a way to circumvent this problem?
