### ISSUE TITLE
(IMPORT FAILED) ComfyUI Noise

### ISSUE THREAD

**Issue by brbbbq** [BlenderNeko/ComfyUI_Noise#31]
I got this error when trying to install the nodes:
```
Traceback (most recent call last):
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise\nodes.py", line 10, in <module>
    import comfy.sampler_helpers
ModuleNotFoundError: No module named 'comfy.sampler_helpers'

Cannot import C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise module for custom nodes: No module named 'comfy.sampler_helpers'
```

To be fair, I've been having similar issues trying to install other nodes recently.

**Comment by HydraBucket** [comment]
im also having this error

**Comment by FlashOrange** [comment]
just copy https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/sampler_helpers.py to comfy folder。
